<a href="https://colab.research.google.com/github/ahmedsha8880-glitch/Math-workshop/blob/main/workshop_6(shahid).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# -*- coding: utf-8 -*-
"""
This is a script file for Week 5 Workshop.

Author: Shahid Ahmed
"""

import numpy as np

if __name__ == "__main__":

    """ Problem 1: Create a 2D ndarray (Matrix) of type Float,
    e.g., [[1,2,3],[4,5,6],[7,8,9]]
    and see its properties/attributes """

    arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
    print("Array =")
    print(arr)
    print("Data Type of the Array =", arr.dtype)
    print("Number of dimensions of the Array =", arr.ndim)
    print("Shape of the Array =", arr.shape)
    print("Size of the Array =", arr.size)
    print("Number of bytes used by each element of the Array =", arr.itemsize)
    print("Total bytes used by the Array =", arr.nbytes)
    print("Memory layout information =", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array = float64
Number of dimensions of the Array = 2
Shape of the Array = (3, 3)
Size of the Array = 9
Number of bytes used by each element of the Array = 8
Total bytes used by the Array = 72
Memory layout information =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
#PROBLEM 2

""" Problem 2: Create a 2D ndarray (Matrix) of shape (4,5) with all elements
equal to 3.0 and print the matrix. """

arr2 = 3 * np.ones((4,5), dtype=float)
print("Array = ")
print(arr2)
print("Shape = ", arr2.shape)
print("DataType = ", arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


In [ ]:
#PROBLEM 3

""" Problem 4: Construct a matrix [a_ij] of shape (3,3) whose elements
are given by a_ij = 1/2 |i - 3j|.
This is the same question in the Lecture slide. """

# Note: in Python indexing starts at 0
arr4 = np.fromfunction(lambda i, j: np.abs(i + 1 - 3*(j + 1)) / 2, (3, 3), dtype=int)
print("Array = ")
print(arr4)
print("Shape = ", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
DataType =  float64


In [ ]:
#PROBLEM 4

""" Problem 4: Construct a matrix [a_ij] of shape (3,3) whose elements
are given by a_ij = 1/2 |i - 3j|.
This is the same question in the Lecture slide. """

# Note: in Python indexing starts at 0
arr4 = np.fromfunction(lambda i, j: np.abs(i + 1 - 3*(j + 1)) / 2, (3, 3), dtype=int)
print("Array = ")
print(arr4)
print("Shape = ", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
DataType =  float64


In [ ]:
#problem 5

""" Problem: Construct a diagonal matrix of shape (4,4)
whose diagonal elements are [1,2,3,4]. """

import numpy as np

diag_elements = [1, 2, 3, 4]
arr5 = np.diag(diag_elements)

print("Array = ")
print(arr5)
print("Shape = ", arr5.shape)
print("DataType = ", arr5.dtype)

Array = 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape =  (4, 4)
DataType =  int64


In [ ]:
""" Problem 6: Construct a matrix of shape (4,5) with whatever elements,
and then slice it to obtain a matrix of shape (3,3) that contains
only the upper-left portion of the original matrix. """

import numpy as np

# Create a 4x5 matrix
arr6 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20]])

print("Original Array = ")
print(arr6)

# Slice to get upper-left 3x3 matrix
sliced_arr = arr6[:3, :3]

print("Sliced Array (3x3 upper-left) = ")
print(sliced_arr)

print("Shape = ", sliced_arr.shape)
print("DataType = ", sliced_arr.dtype)


Original Array = 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Sliced Array (3x3 upper-left) = 
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
Shape =  (3, 3)
DataType =  int64


#part 2


In [ ]:
import numpy as np

""" Problem 1: Create two matrices A and B and add them.
Observe the result and explain. """

# Matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matrix B
B = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])

# Addition
C = A + B

print("Matrix A = ")
print(A)

print("Matrix B = ")
print(B)

print("A + B = ")
print(C)


Matrix A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B = 
[[1 1 1]
 [2 2 2]
 [3 3 3]]
A + B = 
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [ ]:
import numpy as np

def dot_product(vec1, vec2):
    # flatten the input vectors
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m, n = mat.shape
    p, q = vec.shape

    assert n == p, "The matrix and vector are not compatible for multiplication!"

    # create a ndarray to store the result
    result = np.zeros((m, q), dtype=float)

    # Loop to perform Matrix-Vector product
    for i in range(m):
        result[i] = dot_product(mat[i, :], vec)

    return result


if __name__ == "__main__":

    # Part 2: Problem 2
    mat1 = np.full((3,3), 3, dtype=int)   # 3×3 matrix filled with 3
    vec1 = np.full((3,1), 2, dtype=int)   # 3×1 vector filled with 2

    print("Matrix = ")
    print(mat1)
    print("Vector = ")
    print(vec1)

    # Call the function
    result1 = matrix_vector_product(mat1, vec1)
    print("Result (Manual) = ")
    print(result1)

    # Check with numpy built-in function
    result2 = mat1 @ vec1
    print("Result (NumPy) = ")
    print(result2)


Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]
Result (Manual) = 
[[18.]
 [18.]
 [18.]]
Result (NumPy) = 
[[18]
 [18]
 [18]]


In [ ]:
import numpy as np

def dot_product(vec1, vec2):
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))


def matrix_matrix_product(A, B):
    m, n = A.shape
    p, q = B.shape

    assert n == p, "Matrices are not compatible for multiplication!"

    # Result matrix of shape (m x q)
    result = np.zeros((m, q), dtype=float)

    # Compute matrix-matrix product
    for i in range(m):
        for j in range(q):
            result[i, j] = dot_product(A[i, :], B[:, j])

    return result


if __name__ == "__main__":

    # Example matrices
    A = np.array([[1, 2, 3],
                  [4, 5, 6]])

    B = np.array([[7, 8],
                  [9, 10],
                  [11, 12]])

    print("Matrix A =")
    print(A)

    print("Matrix B =")
    print(B)

    # Custom result
    custom_result = matrix_matrix_product(A, B)
    print("Custom Matrix-Matrix Product =")
    print(custom_result)

    # NumPy built-in result
    numpy_result = A @ B
    print("NumPy dot() Result =")
    print(numpy_result)


Matrix A =
[[1 2 3]
 [4 5 6]]
Matrix B =
[[ 7  8]
 [ 9 10]
 [11 12]]
Custom Matrix-Matrix Product =
[[ 58.  64.]
 [139. 154.]]
NumPy dot() Result =
[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

def is_symmetric(matrix):
    # A matrix is symmetric if it is equal to its transpose
    return np.array_equal(matrix, matrix.T)


if __name__ == "__main__":

    # Example matrices
    A = np.array([[1, 2, 3],
                  [2, 5, 6],
                  [3, 6, 9]])

    B = np.array([[1, 0, 2],
                  [0, 5, 7],
                  [3, 7, 9]])

    print("Matrix A =")
    print(A)
    print("Is A symmetric? ->", is_symmetric(A))

    print("\nMatrix B =")
    print(B)
    print("Is B symmetric? ->", is_symmetric(B))


Matrix A =
[[1 2 3]
 [2 5 6]
 [3 6 9]]
Is A symmetric? -> True

Matrix B =
[[1 0 2]
 [0 5 7]
 [3 7 9]]
Is B symmetric? -> False
